TOPDIR = ..
LIB = runtime.a
CSRCS = runtime.c

CFLAGS = -fPIC -O2 -fvisibility=hidden -I${TOPDIR}/include -pthread

include ${TOPDIR}/make/comm.mk
include ${TOPDIR}/make/c.mk
include ${TOPDIR}/user.mk
