TOPDIR = ..
PROG = patcher
CXXSRCS = main.cpp

CFLAGS = -I ${ZYDIS}/include -g -O2
LDFLAGS = -L ${ZYDIS}/lib -lZydis

include ${TOPDIR}/make/comm.mk
include ${TOPDIR}/make/cxx.mk
include ${TOPDIR}/user.mk
